# this should be layered on top of docker-compose.yml
services:

  hybrid_node:
    container_name: test_hybrid_node
    build:
      context: .
      dockerfile: dockerfiles/hybrid_node.dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1
        delay: 10s
    depends_on:
      - redis
      - test_db
    volumes:
      - .:/app
    entrypoint: ["python", "-u", "/app/validator/hybrid_node/src/main.py"]
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      ENV: test
      NETUID: 19

  chain_node:
    container_name: test_chain_node
    build:
      context: .
      dockerfile: dockerfiles/chain_node.dockerfile
    depends_on:
      - test_db
      - redis
    volumes:
      - .:/app
    entrypoint: ["python", "-u", "/app/validator/chain_node/src/main.py"]
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      RUN_ONCE: "true"
      DUMMY: "true"
      NETUID: 19
      ENV: test
      NETWORK: test
      SECONDS_BETWEEN_SYNC: 60

  control_node:
    container_name: test_control_node
    build:
      context: .
      dockerfile: dockerfiles/control_node.dockerfile
    depends_on:
      - redis
      - test_db
    volumes:
      - .:/app
    entrypoint: ["python", "-u", "/app/validator/control_node/src/main.py"]
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      ENV: test

  test_db:
    container_name: test_db
    image: postgres:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST: test_db
    ports:
      - "5433:5432"

  dbmate:
    image: amacneil/dbmate
    volumes:
      - ./validator/db:/db
    command: up
    depends_on:
      test_db:
        condition: service_started
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: test_db
      DATABASE_URL: "postgres://test_user:test_password@test_db:5432/test_db?sslmode=disable"

  test_adminer:
    image: adminer
    restart: always
    ports:
      - 5052:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    depends_on:
      - test_db

volumes:
  postgres_data:
