[tool.pyright]
exclude = ["**/node_modules", "**/__pycache__", "**/test_*.py", "**/venv/*"]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.10"
pythonPlatform = "Linux"
reportMissingModuleSource = false

[tool.typos.default]
extend-ignore-identifiers-re = [
    "datas",
]

[tool.typos.default.extend-words]
ninteen = "nineteen"