{
 "title": "Validator General",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "task",
    "query": {
     "query": "label_values(validator_query_node_query_streaming_contender_tokens_per_sec, task)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TPS by Task and Contender",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "tokensps" } },
   "targets": [
    {
     "expr": "validator_query_node_query_streaming_contender_tokens_per_sec{task=~\"$task\"}",
     "legendFormat": "{{task}} - {{hotkey}}"
    }
   ]
  },
  {
   "title": "Selections by Task and Contender",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "validator_query_node_contender_selections_total{task=~\"$task\"}",
     "legendFormat": "{{task}} - {{hotkey}}"
    }
   ]
  },
  {
   "title": "Tokens Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "validator_hybrid_node_text_tokens_per_sec",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "/v1/chat/completions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_response_size_bytes_count{exported_job=\"hybrid_node\", http_target=\"/v1/chat/completions\"}[1m]) * 60",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "/v1/text-to-image",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_response_size_bytes_count{exported_job=\"hybrid_node\", http_target=\"/v1/text-to-image\"}[$__rate_interval])",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "/v1/image-to-image",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_response_size_bytes_count{exported_job=\"hybrid_node\", http_target=\"/v1/image-to-image\"}[$__rate_interval])",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Queries Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(validator_hybrid_node_process_queries_total{exported_job=\"hybrid_node\"}[$__rate_interval]) * 60",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Queries Failed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "validator_hybrid_node_process_failed_queries_total",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Queries Processing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "validator_hybrid_node_src_concurrent_queries_processing_ratio",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Synthetic Remaining Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "validator_control_node_synthetic_cycle_schedule_remaining_requests{exported_job=\"control_node\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Synthetic Requests To Skip",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "validator_control_node_synthetic_cycle_requests_to_skip{exported_job=\"control_node\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Validator Image Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(validator_hybrid_node_image_success_total{exported_job=\"hybrid_node\"}[1m]) * 60",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Validator Image Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(validator_hybrid_node_image_error_total{exported_job=\"hybrid_node\"}[1m]) * 60",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Validator Text Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(validator_hybrid_node_text_success_total{exported_job=\"hybrid_node\"}[1m]) * 60",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Validator Text Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(validator_hybrid_node_text_error_total{exported_job=\"hybrid_node\"}[1m]) * 60",
     "legendFormat": "{{http_target}}"
    }
   ]
  },
  {
   "title": "Validator Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{service_name=~\"control_node|hybrid_node\"} | label_format level=detected_level | line_format `{{.service_name }} - {{__line__}}`"
    }
   ]
  }
 ]
}